const falhas = [
  "Uma intensa atividade cerebral extraplanar chega até você, inundando-o com conhecimento muito avançado para os padrões artonianos. Você fica atordoado por 1d6 rodadas, mas após isso recebe +1 em Inteligência, Sabedoria ou Carisma (escolhido aleatoriamente; uma vez por personagem).",
  "A alça do seu escudo se desprende. Você pode gastar uma ação de movimento para soltar o escudo e não sofrer penalidades, ou lutar dessa forma e sofrer –2 em testes de ataque. Consertar a alça leva 1 minuto.",
  "Você nota que está muito fora de forma e lembra que passou a última semana enfurnado na taverna, comendo e bebendo demais. Você fica exausto até o fim do combate.",
  "Você é atingido por uma onda súbita de azar e incompetência generalizada. Role duas vezes nesta tabela.",
  "Em um movimento louco que irá entrar para os anais dos manuais de combate, você embainha sua arma sem querer.",
  "Você tropeça em uma tartaruga invisível imaginária morta e cai de cara no chão. Além de ficar caído, você sofre –2 em testes baseados em Carisma por um dia, pelo rosto amassado.",
  "Cheiro ruim. Quem foi? Não importa. Você perde 1d4 PM e fica fraco por 1d4 rodadas.",
  "Ataque de riso! Você acha muita graça de algo e, enquanto ri sem controle por 1d4 rodadas, fica lento e sofre –2 em testes de ataque.",
  "Cãibra na perna: você fica lento e sofre –5 em Atletismo até o fim da cena.",
  "Uma velha ferida se abre. Você perde 5 PV e fica abalado por 1d4 rodadas.",
  "Casca de banana: um clássico! Você cai de costas no chão e perde 1d6 PV.",
  "Ops! Você pisa em um inseto grande e nojento. Perca 1 rodada limpando a gosma da bota ou sofra –1 em testes de ataque e de resistência até fazer isso.",
  "Presságio de morte... A sua! O próximo ataque que você sofrer será um acerto crítico, ou a próxima habilidade que lhe causar dano causará o dobro de dano.",
  "Uma onda de energia negativa atinge o campo de batalha, fazendo com que um inimigo que já havia sido derrotado se erga como um zumbi! O inimigo tem as mesmas estatísticas, mas é um morto-vivo e tem Fraqueza Zumbi (Defesa igual à do inimigo +10).",
  "Uma área de Tormenta aparece debaixo dos seus pés! Você perde 2d12 pontos de vida (Ref CD 25 reduz à metade), mas recebe um poder da Tormenta escolhido pelo mestre até o fim da cena.",
  "Você sente uma fisgada e fica vulnerável por 1d4 rodadas.",
  "Fenômeno mágico! O céu fica rosa, deuses passam voando entre as nuvens ou chovem sapos. Todos no combate ficam olhando, e ficam pasmos por 1 rodada. Após a pausa, todos rolam iniciativa novamente.",
  "Cãibra no pescoço: –5 em Percepção e Reflexos por 1d4 rodadas.",
  "Fenômeno climático imprevisível: um relâmpago atinge seu braço erguido no meio do golpe. Você sofre 6d8 pontos de dano de eletricidade.",
  "Descoordenação! Você derruba um item empunhado aleatório.",
  "Você abre sua guarda! Um oponente adjacente à escolha do mestre pode realizar um ataque imediato contra você.",
  "Fome repentina: você tem 2 rodadas para comer uma ração de viagem ou fica fatigado.",
  "Sua arma se desgasta com o golpe, sendo destruída, a menos que seja mágica.",
  "Optando por garantir pelo menos um ataque bem-sucedido, na próxima rodada você deve usar o seu melhor ataque contra o oponente mais fraco.",
  "Você tenta vencer o combate “no grito”. Na próxima rodada, deve fazer um teste de Intimidação para assustar um oponente, ou perde sua rodada.",
  "Tomado por medo, indecisão ou outro sentimento qualquer, você trava! Na próxima rodada, você fica pasmo.",
  "Ato anti-heroico: você faz algo indigno de um herói, como acovardar-se frente a um ataque, usar um inocente como escudo ou lutar sujo. Você perde 1d4+1 PM.",
  "Sua pistola explode na sua mão e o tiro sai pela culatra! Você sofre 3d6 pontos de dano de fogo e sua arma é destruída.",
  "Sequência de desastres: até o fim da cena, seu próximo acerto crítico será substituído por uma falha crítica.",
  "Escorregão! Nada grave, a menos que você esteja na beira de um precipício. Nesse caso, faça um teste de Reflexos (CD 20). Se falhar, agora você está em queda livre!",
  "Você se cansa de ser chamado de “fracolino das magias” e vai mostrar que pode vencer uma luta com seus punhos. Nas próximas 2 rodadas, você não pode lançar magias.",
  "Seu ataque rebate no oponente, atingindo você mesmo. Sofra metade do dano que causaria caso tivesse acertado.",
  "Um rato enorme morde sua perna e, após 1 dia, você é infectado com varíola.",
  "Calafrio: um espírito ou alma penada deixa-o muito nervoso! Você fica apavorado por 1 rodada.",
  "Dor de cabeça súbita: você fica alquebrado até o fim da cena.",
  "Má decisão: quem nunca tomou? O mestre escolhe o alvo do seu próximo ataque (não pode ser um aliado).",
  "Enjoo súbito! Tanto sangue revira seu estômago. Você fica enjoado por 1d4 rodadas.",
  "Você nota algo muito interessante do outro lado do campo de batalha. Na próxima rodada, você deve usar uma ação completa para se movimentar até lá.",
  "Você faz uma bobagem e mostra que não é tão poderoso. Seus oponentes ficam motivados, recebendo +2 nos testes de ataque contra você até o fim da cena.",
  "Problema na mochila. Um item que você esteja carregando se quebra. Se for uma poção ou item alquímico, você sofre o efeito dele.",
  "Mil maldições! Você sofre –5 em todos os testes por 2 rodadas. Depois disso, o aliado mais próximo de você sofre esta mesma maldição por 2 rodadas, e assim sucessivamente.",
  "Seu elmo gira e tapa sua visão! Você fica cego até gastar uma ação padrão para ajustá-lo.",
  "Visão profana: você vê uma aparição de um deus inimigo da sua divindade padroeira. Você fica desprevenido nessa rodada, e na próxima rodada sofre –5 em todos os testes.",
  "Um cisco entra no seu olho! Você fica cego por 1d4 rodadas.",
  "Um vento frio sopra em suas costas... Você fica abalado por 1d4 rodadas.",
  "Você decide tentar uma técnica de defesa inovadora. Infelizmente, ela não é muito eficaz. Você fica vulnerável por 1d4 rodadas.",
  "Subitamente, você nota que está fora de forma e que todas aquelas noites na taverna estão cobrando seu preço. Você fica fatigado até o fim da cena.",
  "Você tropeça e desequilibra-se. Você fica caído e vulnerável até se levantar.",
  "Sua aljava ou cartucheira cai no chão e sua munição se espalha. Sempre que quiser recarregar sua arma, você deve gastar uma ação de movimento para recolher a munição. Recolher tudo de uma só vez é uma ação completa.",
  "Uma aranha pica sua perna e, após 1 dia, você contrai a doença tremores (Tormenta20, p. 318).",
  "Seu cinto se abre e suas calças caem! Você fica lento e vulnerável até gastar uma ação padrão para se vestir.",
  "Que combate tedioso! Você para de prestar atenção a seus oponentes e começa a examinar seus arredores. Você fica desprevenido por 1d4 rodadas, mas pode fazer um teste de Percepção (CD 20) como uma ação livre. Se passar, o mestre pode lhe fornecer alguma informação.",
  "Sorvedouro de magia: devido a um fenômeno arcano imprevisível, você perde 1d10 PM.",
  "Derrame: uma súbita pontada seguida de dor de cabeça… Tudo fica preto. Será o fim? Faça um teste de Sabedoria (CD 10). Se passar, você fica alquebrado. Se falhar, você morre.",
  "Um trovão ressoa alto e perto demais. Você fica abalado por 1 rodada e surdo por 1d4 rodadas.",
  "O que você está esperando? Sonhando acordado, você sofre –10 na ordem de iniciativa pelo resto do combate.",
  "Raiva aleatória: você entra em fúria, como um bárbaro de 1° nível. Se já estiver em fúria, ela acaba.",
  "Golpe nos olhos: se você sofrer um acerto crítico nesse combate, seus olhos se inundam de sangue, ou seus globos oculares saltam para fora das órbitas. Seja como for, você fica cego até receber pelo menos 20 pontos de cura mágica.",
  "Uma onda de energia positiva atinge o campo de batalha, mas só do lado dos inimigos... Todos os adversários recuperam 2d8+2 pontos de vida por patamar do grupo.",
  "Pontada no peito: –5 em Fortitude até o fim da cena.",
  "Uma mão esquelética surge do chão e puxa seu pé. Você fica agarrado até conseguir se soltar (exige gastar uma ação padrão e passar num teste de Luta contra CD 20).",
  "Seu sangue esquenta e você se enfurece. Você sofre –2 em testes até acertar um ataque corpo a corpo em um inimigo.",
  "Ferimentos antigos incomodam... Seus PV máximos são reduzidos em um valor igual ao seu nível até o fim do dia.",
  "Hã? Borboletas voejantes capturam toda a sua atenção. Faça um teste de Sabedoria (CD 10). Se falhar, você fica fascinado até o fim do seu próximo turno. O quê?",
  "O sol, uma magia ou uma tocha nas proximidades atrapalham sua visão: você sofre –5 em Reflexos até o fim da cena.",
  "Você bate com o mindinho em algo e é tomado por agonia! Ui! Não pode fazer ataques desarmados durante a próxima rodada e sofre –2 em testes baseados em Destreza até o fim da cena.",
  "Você engasga com poeira e fica fatigado até o fim do seu próximo turno.",
  "Você termina o seu golpe com uma pose de grande efeito teatral, mas baixa qualidade combativa. Você fica desprevenido até o fim da sua próxima rodada.",
  "Sua granada ou preparado arremessado cai perto do seu alvo, mas não explode. O alvo faz um teste de Reflexos (CD 15) como uma reação. Se passar, ele chuta o item de volta para você. Você então se torna o novo alvo do item!",
  "Sua bolsa de moedas voa longe e espalha todos os seus tibares pelo chão. Tomara que você vença o combate e não precise fugir.",
  "Ops! Faça um ataque imediato contra um aliado em seu alcance. Esse aliado está desprevenido contra esse ataque.",
  "Energia dissipada: se você usou seu ataque em conjunto com uma habilidade que custe PM, gaste o dobro de PM.",
  "Com os movimentos bruscos do combate, sua roupa se rasga ou uma fivela da sua armadura se abre. Perca um item vestido, decidido aleatoriamente. Após o combate, você pode gastar 1 hora para remendar o item.",
  "Um preparado que você esteja carregando explode em sua mão. Sofra o efeito do item (sem direito a teste de resistência).",
  "Palavra amiga! Você gasta sua próxima ação padrão para fazer um teste de Diplomacia (CD 30). Se passar, um inimigo não vê motivos para atacá-lo.",
  "Uma de suas poções ou itens alquímicos à escolha do mestre se quebra. Sofra o efeito do item.",
  "Fogo amigo: você acerta um aliado que esteja lutando em corpo a corpo com o alvo original do seu ataque.",
  "Uma cobra morde seu pé. Você perde 1d12 PV por veneno.",
  "Bobagem suprema: você tropeça e cai de mau jeito, torcendo o tornozelo e correndo o risco de quebrar o pescoço! Faça um teste de Destreza (CD 10). Se passar, você fica lento. Se falhar, quebra o pescoço e morre.",
  "Você é tomado pela raiva da batalha e para de pensar direito. Você fica frustrado e, até o fim do seu próximo turno, não pode usar habilidades.",
  "Ataque cardíaco: argh! Dor no peito, falta de ar, braço esquerdo inutilizado por 1d6 rodadas. Faça um teste de Constituição (CD 10). Se passar, fica fatigado. Se falhar, morre.",
  "Compulsão autopreservativa: você fica indefeso até usar um item ou habilidade que recupere seus PV ou PM.",
  "Esse último golpe foi mais forte do que parecia! Você sofre de novo o dano do último ataque ou habilidade que o atingiu, mas como dano não letal.",
  "Um inseto entra na sua orelha bem no momento do golpe. Gaste uma ação de movimento para remover o incômodo ou sofra –2 em testes até ele ir embora, em 2d4 rodadas.",
  "Tiro no pé — literalmente! Você causa o dano de um ataque à distância em si mesmo e fica lento por 1d4 rodadas.",
  "Você chuta uma pedra! Você fica lento até o fim da cena.",
  "Seu movimento com o ataque foi forte demais e sua arma voa longe. Ela cai a 9m de você, em uma direção aleatória.",
  "Pessimismo súbito: mesmo que o combate esteja indo bem, você se sente derrotado e inútil. Você fica alquebrado até o fim da cena.",
  "Você tem uma tontura súbita. Você fica enjoado e vulnerável por 1d4 rodadas.",
  "Sua mochila se abre e espalha todos os seus itens no chão.",
  "Você puxa demais a corda do seu arco ou besta! Ela se rompe, atingindo seu braço. Você sofre 1d6 pontos de dano de corte e a arma é destruída.",
  "A tocha ou lampião que você carrega subitamente se apaga.",
  "Cãibra no braço esquerdo: você deixa cair o que está segurando e não consegue usar o braço por 1d4 rodadas.",
  "Você se distrai e baixa sua guarda. –5 na Defesa por 1 rodada.",
  "Tentando atingir mais longe do que deveria, você distende o braço. –5 no próximo teste de ataque.",
  "Cãibra no braço direito: você deixa cair o que está segurando e não consegue usar o braço por 1d4 rodadas.",
  "Um meteoro cai em você! Você sofre 6d6 pontos de dano de impacto e 6d6 pontos de dano de fogo (Ref CD 25 reduz à metade).",
  "Você tropeça em sua própria capa, calça ou saia: cai no chão e sofre 1d6 pontos de dano de impacto.",
  "Zupt! A lâmina de sua espada, cabeça de seu machado etc. solta-se e voa para longe. A arma é destruída.",
  "Visão divina: você vê uma aparição de seu deus. Você fica indefeso nessa rodada, mas recebe +5 em testes até o fim da cena.",
];

export async function rollFail() {
  const roll = new Roll("1d100");
  await roll.evaluate();
  const index = roll.total - 1;
  const text = falhas[index];

  const flavor = `
  <div>
  <span style="font-size: 1.5em">Efeito</span>
  </br>
  <span style="font-weight: bold;">${text}</span>
  </div>`;
  roll.toMessage({
    speaker: ChatMessage.getSpeaker(),
    flavor,
  });
}
