const names = {
  Humano: [
    "Hekker",
    "Dinlana",
    "Mouvo",
    "Khalmyrian",
    "Pidder",
    "Baziare",
    "Vikkander",
    "Andara",
    "Darezio",
    "Natuwa",
    "Orsen",
    "Kevan",
    "Tariana",
    "Valk",
    "Ergol",
    "Rilena",
    "Neria",
    "Vosser",
    "Zilth",
    "Xandara",
    "Belazio",
    "Egriana",
    "Molden",
    "Nilga",
    "Phadra",
    "Riales",
    "Portina",
    "Holdavir",
    "Yohll",
    "Astri",
    "Merthik",
    "Zasdree",
    "Agnigg",
    "Shivar",
  ],
  Anão: [
    "Bobrum",
    "Arthoram",
    "Dharumm",
    "Dharva",
    "Khodharann",
    "Thyrmah",
    "Movadhimm",
    "Kharadhan",
    "Vosthanum",
    "Dhenomm",
    "Khetradann",
    "Vorthrerem",
    "Theratra",
    "Mondhom",
    "Dhozardhum",
    "Hiradramm",
    "Ghoridri",
    "Mondharum",
    "Dhervadhara",
    "Heredimatrim",
    "Dhorelonn",
    "Khedruenn",
    "Thovattor",
    "Mortherimm",
    "Vothramin",
    "Gaudrimm",
    "Darandor",
    "Vormmir",
    "Dondarann",
    "Thammira",
    "Gadhara",
    "Rhommar",
    "Drovathir",
    "Bovidharimm",
  ],
  Dahllan: [
    "Calixta",
    "Tulipa",
    "Briara",
    "Nalia",
    "Íris",
    "Lily",
    "Suyane",
    "Rennia",
    "Asteria",
    "Dahl",
    "Ione",
    "Estrelícia",
    "Fresia",
    "Ianth",
    "Gardenia",
    "Ninfania",
    "Zandedía",
    "Dianthia",
    "Calen",
    "Neruma",
    "Flora",
    "Gerbera",
    "Hortensia",
    "Ixare",
    "Choe",
    "Trelitzia",
    "Echaea",
    "Alpinia",
    "Limeria",
    "Crisântemo",
    "Ergilla",
    "Hedera",
    "Ocarya",
    "Lisana",
  ],
  Elfo: [
    "Assalan",
    "Dandalla",
    "Thissalorian",
    "Yollaria",
    "Mivandre",
    "Aerillodala",
    "Phasdalan",
    "Govandar",
    "Morvalane",
    "Cissalia",
    "Erhamadoren",
    "Tallamasser",
    "Nieelerendalan",
    "Yavallan",
    "Manalliare",
    "Ellanva",
    "Gilliane",
    "Narallandan",
    "Ansalloron",
    "Ollarandhan",
    "Gandolarae",
    "Glorillaniavar",
    "Nidallarian",
    "Denore",
    "Allava",
    "Ceris",
    "Mantalla",
    "Dallantalla",
    "Talleslena",
    "Allarandre",
    "Vallissaris",
    "Nillandra",
    "Missariel",
    "Yanara",
  ],
  Goblin: [
    "Molon",
    "Kralik",
    "Tarak",
    "Blakon",
    "Xismo",
    "Zakor",
    "Takor",
    "Tuzu",
    "Tapak",
    "Kinika",
    "Tavog",
    "Golak",
    "Bogg",
    "Zitt",
    "Vulma",
    "Karcar",
    "Gogola",
    "Gork",
    "Pakkug",
    "Dondon",
    "Raska",
    "Digg",
    "Pottak",
    "Kazunk",
    "Bink",
    "Fahuk",
    "Matran",
    "Xesto",
    "Kovvo",
    "Badum",
    "Geria",
    "Kekke",
    "Orgg",
    "Nithuk",
  ],
  Hynne: [
    "Dulla",
    "Donatto",
    "Minna",
    "Colita",
    "Melano",
    "Ortho",
    "Guévio",
    "Lelia",
    "Diggo",
    "Bolim",
    "Everla",
    "Nando",
    "Moringa",
    "Basil",
    "Tenga",
    "Malvio",
    "Tom",
    "Dida",
    "Gelisa",
    "Binoto",
    "Tutu",
    "Lanito",
    "Aggario",
    "Prilla",
    "Poltan",
    "Bilda",
    "Moira",
    "Vanne",
    "Gombo",
    "Erdesta",
    "Lazzo",
    "Pimb",
    "Orrs",
    "Ollir",
  ],
  Minotauro: [
    "Caius",
    "Lorcus",
    "Crassis",
    "Tissius",
    "Mantorio",
    "Astilus",
    "Khoskar",
    "Blarandus",
    "Taelio",
    "Cradus",
    "Zhabur",
    "Halssinos",
    "Ianaris",
    "Iosalis",
    "Tarkan",
    "Erius",
    "Eradorio",
    "Ocretio",
    "Maxandus",
    "Issius",
    "Lekariu",
    "Pallis",
    "Ghandor",
    "Quindalio",
    "Spurtius",
    "Pondus",
    "Sarius",
    "Tenalidis",
    "Lortamus",
    "Gaellio",
    "Daxidus",
    "Flanattus",
    "Maxxius",
    "Avenius",
  ],
  Qareen: [
    "Narav",
    "Quedan",
    "Sarid",
    "Ahtan",
    "Alzon",
    "Maquet",
    "Arid",
    "Bihalla",
    "Tahlid",
    "Ubb",
    "Rahllira",
    "Jehel",
    "Murad",
    "Zilla",
    "Hesan",
    "Pharid",
    "Narud",
    "Suhed",
    "Dazalid",
    "Zorima",
    "Quotora",
    "Ynari",
    "Jolid",
    "Tazif",
    "Palan",
    "Zaldonay",
    "Alnari",
    "Jeddar",
    "Ishazar",
    "Belnira",
    "Haddan",
    "Olara",
    "Persite",
    "Razzi",
  ],
};

export async function randomNames() {
  const content =
    `<span>Random Names</span> </br>` +
    Object.entries(names)
      .map(([key, array]) => {
        const buttons = `<button class="random-name" data-id="${key}" key="${key}" style="width: 100%; margin: 4px 0; padding: 8px; display: flex; align-items: center; gap: 10px; border: 4px 4px 4px px">
    <span style="flex-grow: 1; text-align: center;">${key}</span>
    </button>`;
        return `<div>${buttons}</div>`;
      })
      .join("");

  new Dialog({
    title: `Random Names`,
    content: `<div>${content}</div>`,
    buttons: {},
    render: async (hml) => {
      hml.find(".random-name").click(async (ev) => {
        const race = ev.currentTarget?.dataset?.id;
        const roll = new Roll("1d100");
        await roll.evaluate();
        const index = Math.ceil((roll.total - 1) / 3);
        const name = names[race][index];

        roll.toMessage({
          speaker: ChatMessage.getSpeaker(),
          flavor: `Raça: ${race} - Nome: ${name}`,
        });
      });
    },
  }).render(true);
}
